Feature branch
kalavhan/enumerables-ruby pull request #1
Opened 2019-12-06 21:33 UTC by kalavhan

pull request for review

2019-12-06 22:09 UTC, suretrust requested changes
Hi @kalavhan,

### Great job thus far, :raised_hands: however, there are some issues with some of the enumerable methods, please see my comments on your code.

**Kindly submit for another code review once these issues have been fixed.** _Happy coding!_ :tada:

2019-12-06 22:09 UTC, suretrust commented on main.rb
> +  end
- [x]  Enumerables my_each returns an Enumerator if no block is given.

`[1,2,3,4,5].my_each` should return `#<Enumerator: [1, 2, 3, 4, 5]:my_each>`

2019-12-06 22:09 UTC, suretrust commented on main.rb
> +  end
- [x]  Enumerables my_each_with_index returns an Enumerator if no block is given.

`[1,2,3,4,5].my_each_with_index` should return `#<Enumerator: [1, 2, 3, 4, 5]:my_each_with_index>`

2019-12-06 22:09 UTC, suretrust commented on main.rb
> +  end
- [x]  Enumerables my_select returns an Enumerator if no block is given.

`[1,2,3,4,5].my_select` should return `#<Enumerator: [1, 2, 3, 4, 5]:my_select>`

2019-12-06 22:09 UTC, suretrust commented on main.rb
> +  end
- [x] Enumerables my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

- [x] Enumerables my_all? when no block or argument is given returns true when none of the collection members are false or nil.
`[1,2,3].my_all?` should return `true` since the array doesn't contain `false` or `nil`
- [x] Enumerables my_all? when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
`[].my_all?(1)' should return `true`.

2019-12-06 22:09 UTC, suretrust commented on main.rb
> +  end
- [x] Enumerables my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
`[1,false,nil].my_any?` should return `true`
- [x] Enumerables my_any? when a Regex is passed as an argument returns false if none of the collection matches the Regex
`%w[dog door rod blade].my_any(/d/)` should return `true`.

2019-12-06 22:09 UTC, suretrust commented on main.rb
> +  end
- [x] Enumerables my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
`%w[dog door rod blade].my_none(3)` should return `true`.

2019-12-06 22:09 UTC, suretrust commented on main.rb
> +end
- [ ] Enumerables my_inject combines all elements of enum by applying a binary operation, specified by a block
`[1, 1, 1, 1, 1, 1, 1, 1].my_inject{proc { |sum, n| sum + n }}` should return `#<Proc:0x000055a055166cf0@main.rb:126>`

2019-12-06 22:09 UTC, suretrust commented on main.rb
> +end
Kindly remove this once you are done using it.

2019-12-07 05:47 UTC, whiz25 requested changes
## Good job :+1: 
Nice work implementing the requested changes. I tested your methods and they pass most edge cases however there are some failing. Check my comments and make the requested changes.

### Martin Afani

2019-12-07 05:49 UTC, whiz25 commented on main.rb
> +  end
- [ ] when no block or argument is given returns true when none of the collection members are false or nil
- [ ] when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

2019-12-07 05:50 UTC, whiz25 commented on main.rb
> +  end
- [ ] when no block or argument is given returns true if at least one of the collection is not false or nil

2019-12-07 05:50 UTC, whiz25 commented on main.rb
> +end
- [ ] combines all elements of enum by applying a binary operation, specified by a block
- [ ] when a symbol is specified combines each element of the collection by applying the symbol as a named method

2019-12-09 15:15 UTC, kalavhan commented
Please, in case you were to find any problem with any method, if you were to have the time, add the validations used, in my validations everything seems fine and is hard to figure out what is the meaning of the error observed without the validation used, thank you!

2019-12-09 17:07 UTC, suretrust requested changes

2019-12-09 17:07 UTC, suretrust commented on main.rb
> +end
- [x] Enumerables my_inject combines all elements of enum by applying a binary operation, specified by a block

[1, 1, 1, 1, 1, 1, 1, 1].my_inject{proc { |sum, n| sum + n }} should return `#<Proc:0x000055a055166cf0@main.rb:127>` not `#<Proc:0x0000555c88292748@main.rb:128>`

2019-12-09 17:07 UTC, suretrust commented on main.rb
> +end
- [ ] Enumerables my_inject, when a symbol is specified, combines each element of the collection by applying the symbol as a named method

`Array.new(100) { rand(0...99) }.my_inject(:+)` is not equal to `Array.new(100) { rand(0...99) }.inject(:+)`

2019-12-09 17:11 UTC, suretrust requested changes
Hi @kalavhan,

### Great job thus far, :raised_hands: I can see that you have invested lots of time and resources, but we aren't there yet.

- [x] Please see my comments on your code.

**Kindly submit for another code review once these issues have been fixed.** _Happy coding!_ :tada:

2019-12-09 18:20 UTC, shshamim63 commented
## Status :recycle:  [!! Required Changes !!] :recycle:  
___
Hi @kalavhan :wave: ,
Well done :clap: . All the enumerable methods are working properly. But one issue is blocking me to approve this project. And I am sorry that it was not mentioned above.
___
#### Please follow the instruction below to complete this project.
___
### :spades:  [Mandatory] :spades: 
___
1. There should be a method  `multiply_els`  that uses `my_inject` as described here:
![image](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/multiply_els.png)
2. Are you sure that without disabling the linter check it is not gonna work. If you really have to disable a rule check this [link](https://stackoverflow.com/questions/37228624/rubocop-line-is-too-long-how-to-ignore)
https://github.com/kalavhan/enumerables-ruby/blob/c08a3269c454b9358b63a7e1fbcd7a8169f310f3/main.rb#L3
https://github.com/kalavhan/enumerables-ruby/blob/c08a3269c454b9358b63a7e1fbcd7a8169f310f3/main.rb#L34
https://github.com/kalavhan/enumerables-ruby/blob/c08a3269c454b9358b63a7e1fbcd7a8169f310f3/main.rb#L49
https://github.com/kalavhan/enumerables-ruby/blob/c08a3269c454b9358b63a7e1fbcd7a8169f310f3/main.rb#L64
___
### Please follow the above instructions and send a final review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Slack](Shakhawat Hossain)

2019-12-09 20:25 UTC, suretrust approved these changes
Hi @kalavhan,

### Amazing job! :raised_hands: Let's get this merged! :+1: 

_Good luck with your future projects and happy coding!_ :tada:

2019-12-09 20:36 UTC, merged